
const utility_customer_requirements = {
    aes_indiana: "AES Indiana",
    alabama_power: "Alabama Power",
    alameda_municipal_power: "Alameda Municipal Power",
    alaska_electric_light_and_power: "Alaska Electric Light & Power",
    alaska_power_and_telephone: "Alaska Power & Telephone",
    alliant_energy: "Alliant Energy",
    azusa_light_and_power: "ALP",
    ameren: "Ameren",
    american_electric_power: "American Electric Power",
    anaheim_public_utilities: "Anaheim Public Utilities",
    appalachian_power: "Appalachian Power",
    arizona_public_service: "Arizona Public Service",
    atlantic_city_electric: "Atlantic City Electric",
    atmos_energy: "Atmos Energy",
    aurora_water: "Aurora Water",
    austin_energy: "Austin Energy",
    avista_utilities: "Avista Utilities",
    baltimore_gas_and_electric: "Baltimore Gas & Electric",
    barton_electric: "Barton Village Electric Department",
    bear_valley_electric_service: "Bear Valley Electric Service",
    berkshire_gas: "Berkshire Gas",
    big_rivers_electric_corporation: "Big Rivers Electric Corporation",
    black_hills_energy: "Black Hills Energy",
    burbank_water_and_power: "Burbank Water & Power",
    burlington_electric: "Burlington Electric",
    california_community_power: "California Community Power",
    cape_light_compact: "Cape Light Compact",
    centerpoint_energy: "CenterPoint Energy",
    central_alabama_electric_cooperative: "Central Alabama Electric Cooperative",
    central_coast_community_energy: "Central Coast Community Energy",
    central_hudson_gas_and_electric_corporation: "Central Hudson Gas & Electric Corporation",
    central_maine_power: "Central Maine Power",
    chugach_electric: "Chugach Electric",
    city_and_borough_of_sitka_utilities_department: "City & Borough of Sitka Utilities Department",
    city_of_charlottesville_utilities: "City of Charlottesville Utilities",
    city_of_gunnison_electric: "City of Gunnison Electric",
    city_of_healdsburg_electric_utility: "City of Healdsburg Electric Utility",
    city_of_lodi_electric_utility: "City of Lodi Electric Utility",
    city_of_lompoc_utilities: "City of Lompoc Utilities",
    city_of_ukiah_electric_department: "City of Ukiah Electric Department",
    city_utilities_of_springfield: "City Utilities of Springfield",
    clark_public_utilities: "Clark Public Utilities",
    cleanpowersf: "CleanPowerSF",
    cleco_power: "Cleco Power",
    coast_electric: "Coast Electric",
    colorado_natural_gas: "Colorado Natural Gas",
    colorado_springs_utilities: "Colorado Springs Utilities",
    colton_electric_utility: "Colton Electric Utility",
    columbia_water_and_light: "Columbia Water and Light",
    commonwealth_edison: "Commonwealth Edison",
    conedison: "ConEdison",
    consumers_energy: "Consumers Energy",
    cooperative_energy: "Cooperative Energy",
    cps_energy: "CPS Energy",
    danville_utilities: "Danville Utilities",
    delaware_electric_cooperative: "Delaware Electric Cooperative",
    delmarva_power: "Delmarva Power",
    dixie_electric_cooperative: "Dixie Electric Cooperative",
    dominion_energy: "Dominion Energy",
    dte_energy: "DTE Energy",
    dubois_rec: "Dubois REC",
    duke_energy: "Duke Energy",
    duquesne_light_company: "Duquesne Light Company",
    east_bay_community_energy: "East Bay Community Energy",
    el_paso_electric: "El Paso Electric",
    elizabethtown_gas: "Elizabethtown Gas",
    empire_electric_association: "Empire Electric Association",
    energy_trust_of_oregon: "Energy Trust of Oregon",
    entergy: "Entergy",
    estes_park_power_and_communications: "Estes Park Power & Communications",
    evergy: "Evergy",
    eversource: "Eversource",
    firstenergy_corporation: "FirstEnergy Corporation",
    flathead_electric_cooperative: "Flathead Electric Cooperative",
    florida_keys_electric_coop: "Florida Keys Electric Cooperative Association",
    florida_power_and_light: "Florida Power & Light",
    florida_public_utilities: "Florida Public Utilities",
    fort_collins_utilities: "Fort Collins Utilities",
    georgia_power: "Georgia Power",
    glendale_water_and_power: "Glendale Water and Power",
    glenwood_springs_electric: "Glenwood Springs Electric",
    great_lakes_energy: "Great Lakes Energy",
    green_mountain_power: "Green Mountain Power",
    gunnison_county_electric_association: "Gunnison County Electric Association",
    harrison_remc: "Harrison REMC",
    hawaii_energy: "Hawaii Energy",
    hawaiian_electric: "Hawaiian Electric",
    heartland_remc: "Heartland REMC",
    holy_cross_energy: "Holy Cross Energy",
    idaho_falls_power: "Idaho Falls Power",
    idaho_power: "Idaho Power",
    imperial_irrigation_district: "Imperial Irrigation District",
    independence_power_and_light: "Independence Power and Light",
    indiana_michigan_power: "Indiana Michigan Power",
    indianapolis_power_and_light: "Indianapolis Power & Light",
    island_energy: "Island Energy",
    jackson_electric_membership_corporation: "Jackson Electric Membership Corporation",
    jacksonville_electric_authority: "Jacksonville Electric Authority",
    jacksonville_electric: "Jacksonville Electric Company",
    jay_county_remc: "Jay County Rural Electric Membership Cooperative",
    jersey_central_power_and_light: "Jersey Central Power & Light",
    kansas_city_power_and_light: "Kansas City Power & Light",
    kentucky_power: "Kentucky Power",
    kentucky_utilities: "Kentucky Utilities",
    knoxville_utilities_board: "Knoxville Utilities Board",
    kootenai_electric_coop: "Kootenai Electric Cooperative",
    la_plata_electric_association: "La Plata Electric Association",
    lakeland_electric: "Lakeland Electric",
    lancaster_choice_energy: "Lancaster Choice Energy",
    lassen_municipal_utility_district: "Lassen Municipal Utility District",
    liberty_utilities: "Liberty Utilities",
    lincoln_electric_system: "Lincoln Electric System",
    long_island_power_authority: "Long Island Power Authority",
    longmont_power_and_communications: "Longmont Power & Communications",
    los_angeles_department_of_water_and_power: "Los Angeles Department of Water and Power",
    loveland_water_and_power: "Loveland Water and Power",
    lyndon_electric: "Lyndon Electric Department",
    marin_clean_energy: "Marin Clean Energy",
    memphis_light_gas_and_water: "Memphis Light, Gas and Water",
    metropolitan_edison: "Metropolitan Edison",
    midamerican_energy: "MidAmerican Energy",
    minnesota_power: "Minnesota Power",
    mississippi_power: "Mississippi Power",
    modesto_irrigation_district: "Modesto Irrigation District",
    mohave_electric_coop: "Mohave Electric Cooperative",
    morgan_county_rural_electric_association: "Morgan County Rural Electric Association",
    morrisville_water_and_light: "Morrisville Water & Light",
    mountain_parks_electric: "Mountain Parks Electric",
    mountain_view_electric_association: "Mountain View Electric Association",
    national_grid: "National Grid",
    nebraska_public_power_district: "Nebraska Public Power District",
    new_hampshire_electric_coop: "New Hampshire Electric Co-op",
    new_jersey_natural_gas: "New Jersey Natural Gas",
    new_mexico_gas_company: "New Mexico Gas Company",
    new_york_state_electric_and_gas: "New York State Electric and Gas",
    nicor_gas: "Nicor Gas",
    north_arkansas_electric_coop: "North Arkansas Electric Cooperative",
    north_shore_gas: "North Shore Gas",
    northern_indiana_public_service_company: "Northern Indiana Public Service Company",
    northfield_electric: "Northfield Electric Department",
    northwestern_energy: "Northwestern Energy",
    nv_energy: "NV Energy",
    ohio_edison: "Ohio Edison",
    oklahoma_electric_coop: "Oklahoma Electric Cooperative",
    oklahoma_gas_and_electric: "Oklahoma Gas & Electric",
    omaha_public_power_district: "Omaha Public Power District",
    oncor: "Oncor",
    orange_and_rockland: "Orange & Rockland",
    orange_county_remc: "Orange County REMC",
    orlando_utilities_commission: "Orlando Utilities Commission",
    otter_tail_power_company: "Otter Tail Power Company",
    ozarks_electric_cooperative: "Ozarks Electric Cooperative",
    pacific_gas_and_electric: "Pacific Gas & Electric",
    pacific_power: "Pacific Power",
    palo_alto_utilities: "Palo Alto Utilities",
    parke_county_remc: "Parke County REMC",
    pasadena_water_and_power: "Pasadena Water and Power",
    pearl_river_valley_electric_power_association: "Pearl River Valley Electric Power Association",
    peco: "PECO",
    peninsula_clean_energy: "Peninsula Clean Energy",
    penn_power: "Pennsylvania Power",
    penelec: "Pennsylvania Electric Company",
    peoples_gas: "Peoples Gas",
    pepco: "Pepco",
    pioneer_community_energy: "Pioneer Community Energy",
    platte_river_power_authority: "Platte River Power Authority",
    plumas_sierra_rural_electric_cooperative: "Plumas-Sierra Rural Electric Cooperative",
    portland_general_electric: "Portland General Electric",
    potomac_edison: "Potomac Edison",
    poudre_valley_rural_electric_association: "Poudre Valley Rural Electric Association",
    powering_new_mexico: "Powering New Mexico",
    ppl_electric_utilities: "PPL Electric Utilities",
    public_service_company_of_oklahoma: "Public Service Company of Oklahoma",
    public_service_enterprise_group: "Public Service Enterprise Group",
    puget_sound_energy: "Puget Sound Energy",
    redding_electric_utility: "Redding Electric Utility",
    redwood_city_public_utilities: "Redwood City Public Utilities",
    redwood_coast_energy_authority: "Redwood Coast Energy Authority",
    roseville_electric_utility: "REU",
    rhode_island_energy: "Rhode Island Energy",
    riverside_public_utilities: "Riverside Public Utilities",
    rochester_gas_and_electric: "Rochester Gas and Electric",
    rocky_mountain_power: "Rocky Mountain Power",
    rushshelby_energy: "RushShelby Energy",
    sacramento_municipal_utility_district: "Sacramento Municipal Utility District",
    salt_river_project: "Salt River Project",
    san_diego_gas_and_electric: "San Diego Gas & Electric",
    san_isabel_electric: "San Isabel Electric",
    san_jose_clean_energy: "San José Clean Energy",
    san_miguel_power_association: "San Miguel Power Association",
    sangre_de_cristo_electric_association: "Sangre de Cristo Electric Association",
    santee_cooper: "Santee Cooper",
    seattle_city_light: "Seattle City Light",
    silicon_valley_clean_energy: "Silicon Valley Clean Energy",
    silicon_valley_power: "Silicon Valley Power",
    singing_river_electric_coop: "Singing River Electric Coop",
    solana_energy_alliance: "Solana Energy Alliance",
    sonoma_clean_power: "Sonoma Clean Power",
    south_alabama_electric_coop: "South Alabama Electric Coop",
    south_central_indiana_remc: "South Central Indiana REMC",
    south_jersey_gas: "South Jersey Gas",
    southern_california_edison: "Southern California Edison",
    southern_california_gas: "Southern California Gas",
    southern_indiana_power: "Southern Indiana Power",
    southern_maryland_electric_cooperative: "Southern Maryland Electric Cooperative",
    southern_minnesota_municipal_power_agency: "Southern Minnesota Municipal Power Agency",
    southern_pine_electric: "Southern Pine Electric",
    southwest_gas: "Southwest Gas",
    southwestern_electric_power_company: "Southwestern Electric Power Company",
    springfield_city_water_light_and_power: "Springfield City Water Light and Power",
    stowe_electric: "Stowe Electric Department",
    sulphur_springs_valley_electric_coop: "Sulphur Springs Valley Electric Cooperative",
    swanton_electric: "Swanton Electric",
    tacoma_public_utilities: "Tacoma Public Utilities",
    tallahassee_city_electric_utility: "Tallahassee City Electric Utility",
    tampa_electric: "Tampa Electric",
    tennessee_valley_authority: "Tennessee Valley Authority",
    texas_new_mexico_power: "Texas New Mexico Power",
    the_illuminating_company: "The Illuminating Company",
    tipmont_remc: "Tipmont Rural Electric Membership Cooperative",
    toledo_edison: "Toledo Edison",
    hardwick_electric_department: "Town of Hardwick Electric Department",
    tri_state_generation_and_transmission_association: "Tri-State Generation and Transmission Association",
    trico_electric_coop: "Trico Electric Cooperative",
    trinity_public_utilities_district: "Trinity Public Utilities District",
    truckee_donner_public_utility_district: "Truckee Donner Public Utility District",
    tucson_electric_power: "Tucson Electric Power",
    turlock_irrigation_district: "Turlock Irrigation District",
    ugi_utilities: "UGI Utilities",
    unisource: "Unisource Energy Services",
    united_illuminating: "United Illuminating",
    united_power: "United Power",
    unitil: "Unitil",
    upper_peninsula_power_company: "Upper Peninsula Power Company",
    valley_clean_energy: "Valley Clean Energy",
    verdigris_valley_electric_coop: "Verdigris Valley Electric Cooperative",
    vermont_electric_coop: "Vermont Electric Cooperative",
    vermont_gas_systems: "Vermont Gas Systems",
    enosburg_falls_electric_and_water: "Village of Enosburg Falls Electric and Water Departments",
    johnson_water_and_light: "Village of Johnson Water & Light Department",
    ludlow_electric: "Village of Ludlow Electric Light Department",
    wabash_valley_power_alliance: "Wabash Valley Power Alliance",
    washington_electric: "Washington Electric Co-op",
    washington_gas: "Washington Gas",
    west_penn_power: "West Pennsylvania Power",
    westar_energy: "Westar Energy",
    win_energy_remc: "WIN Energy REMC",
    wisconsin_public_service: "Wisconsin Public Service",
    xcel_energy: "Xcel Energy",
    yampa_valley_electric_association: "Yampa Valley Electric Association",
    not_applicable: "Not Applicable"
  };
  
  export default utility_customer_requirements;